# Generated by Django 3.2.4 on 2021-06-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='mediacategory',
            options={'ordering': ['name'], 'verbose_name': 'Медия категория', 'verbose_name_plural': 'Медиа категории'},
        ),
        migrations.AlterModelOptions(
            name='postmediacategory',
            options={'ordering': ['title'], 'verbose_name': 'Пост Медиа', 'verbose_name_plural': 'Посты Медии'},
        ),
    ]
