# Generated by Django 3.2.4 on 2021-06-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210607_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mediacategory',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='postmediacategory',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
    ]
