# Generated by Django 3.2.4 on 2021-06-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210607_0313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostMediaCategory',
            new_name='PostMedia',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Posts',
        ),
    ]
